// <auto-generated />
using System;
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Context.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    [Migration("20210123114310_i")]
    partial class i
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Assignment")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lib.Entites.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDateTime = new DateTime(2021, 1, 23, 13, 43, 10, 360, DateTimeKind.Local).AddTicks(4265),
                            Name = "System Administrator",
                            Password = "xFK+xtwJ1HCQCerZrGbEp4h+ZSrsKyRTCgJBpl2LKF0eTfX1",
                            Role = "Admin",
                            Username = "sysadmin"
                        });
                });

            modelBuilder.Entity("Lib.Entites.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTopic")
                        .HasColumnType("bit");

                    b.Property<int?>("PostForStoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopicForStoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostForStoryId");

                    b.HasIndex("TopicForStoryId")
                        .IsUnique()
                        .HasFilter("[TopicForStoryId] IS NOT NULL");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Lib.Entites.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Lib.Entites.Post", b =>
                {
                    b.HasOne("Lib.Entites.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lib.Entites.Story", "PostForStory")
                        .WithMany("Posts")
                        .HasForeignKey("PostForStoryId");

                    b.HasOne("Lib.Entites.Story", "TopicForStory")
                        .WithOne("Topic")
                        .HasForeignKey("Lib.Entites.Post", "TopicForStoryId");

                    b.Navigation("Author");

                    b.Navigation("PostForStory");

                    b.Navigation("TopicForStory");
                });

            modelBuilder.Entity("Lib.Entites.Story", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
